### ISSUE TITLE
How do you control graphics on the badger2040?

### ISSUE THREAD

**Issue by colossalchicken** [rp-rs/rp-hal-boards#28]
The only example of using the badger2040 with Rust online seems to be [the example on how to control the blinking light](https://github.com/rp-rs/rp-hal-boards/blob/main/boards/pimoroni_badger2040/examples/badger_blinky.rs).
How do I control graphics? Which library do I need to use?
Pimoroni has a [graphics library](https://github.com/pimoroni/pimoroni-pico/tree/main/libraries/pico_graphics) for c/c++ but that kind-of defeats the purpose of using Rust.

**Comment by 9names** [comment]
https://docs.rs/uc8151/latest/uc8151/

**Comment by 9names** [comment]
I have some basic code using it at https://github.com/9names/badger2040_testing/blob/main/src/main.rs that probably needs updating
