### ISSUE TITLE
Raspberry Pi Pico SD Card Example Error

### ISSUE THREAD

**Issue by NegrilaRares** [rp-rs/rp-hal-boards#68]
Trying to use this in a project but i keep getting this error once i get to the SdCard::new part of the code.

https://github.com/rp-rs/rp-hal-boards/blob/main/boards/rp-pico/examples/pico_spi_sd_card.rs

![image](https://github.com/rp-rs/rp-hal-boards/assets/129112753/386e0784-d5bf-4b39-8e08-1b57dac3b904)

![image](https://github.com/rp-rs/rp-hal-boards/assets/129112753/0100c6de-7972-4037-a474-703a21debfef)

[error.txt](https://github.com/rp-rs/rp-hal-boards/files/15044459/error.txt)

Tried running the example without any changes and i still get the same error.

**Comment by ithinuel** [comment]
I'm a bit confused by the error message. Are you using this hal or embassy?

**Comment by NegrilaRares** [comment]
for my project im trying to make it work on embassy, but the error appears in my project and when i try to build the example

**Comment by NegrilaRares** [comment]
i can give you the error i get when i run the example but thats just a longer list that starts from the SdCard::new line

**Comment by ithinuel** [comment]
I just cloned `rp-hal-boards` and ran `cargo build --example pico_spi_sd_card` from there and everything builds fine.

I think you may have an issue with your setup (Cargo.toml, dependencies etc).
If you upload that to a repo of yours we may be able to help, but I don’t think there’s an issue in this example.

**Comment by NegrilaRares** [comment]
At least now i know its from me ill check my setup and reopen the issue if i don't manage to find the problem on my own.

Thank you for you help and time.
